import XCTest
@testable import ConsoleModels

/// Covers `GeohashGeometry` (geohash string -> lat/lon bounding box -> polygon
/// ring, for the map's "Grid" overlay) and `IntensityNormalization` (the
/// heat-map overlay's alpha/radius scaling). Reference bounds in
/// `testDecodeBoundsMatchesKnownGeohash*` were generated by running the
/// project's own `decodeGeohashBounds` (`lib/shared/pointId.ts`) — the exact
/// server-side algorithm this is a Swift port of — against fixed geohash
/// strings, so these are ground truth, not hand-derived approximations.
final class SpatialGeoMathTests: XCTestCase {

    // MARK: - decodeBounds

    func testDecodeBoundsMatchesKnownGeohashEzs42() throws {
        let bounds = try GeohashGeometry.decodeBounds("ezs42")

        XCTAssertEqual(bounds.south, 42.5830078125, accuracy: 1e-9)
        XCTAssertEqual(bounds.west, -5.625, accuracy: 1e-9)
        XCTAssertEqual(bounds.north, 42.626953125, accuracy: 1e-9)
        XCTAssertEqual(bounds.east, -5.5810546875, accuracy: 1e-9)
    }

    func testDecodeBoundsMatchesKnownGeohashU4pruy() throws {
        let bounds = try GeohashGeometry.decodeBounds("u4pruy")

        XCTAssertEqual(bounds.south, 57.645263671875, accuracy: 1e-9)
        XCTAssertEqual(bounds.west, 10.404052734375, accuracy: 1e-9)
        XCTAssertEqual(bounds.north, 57.6507568359375, accuracy: 1e-9)
        XCTAssertEqual(bounds.east, 10.4150390625, accuracy: 1e-9)
    }

    func testDecodeBoundsMatchesKnownGeohashForBonamoussadiCell() throws {
        // encodeGeohash(4.05, 9.74, 6) from the real TS implementation.
        let bounds = try GeohashGeometry.decodeBounds("s0wzj9")

        XCTAssertEqual(bounds.south, 4.0484619140625, accuracy: 1e-9)
        XCTAssertEqual(bounds.west, 9.73388671875, accuracy: 1e-9)
        XCTAssertEqual(bounds.north, 4.053955078125, accuracy: 1e-9)
        XCTAssertEqual(bounds.east, 9.744873046875, accuracy: 1e-9)
    }

    func testDecodeBoundsIsCaseInsensitiveAndTrimsWhitespace() throws {
        let lower = try GeohashGeometry.decodeBounds("u4pruy")
        let upperWithWhitespace = try GeohashGeometry.decodeBounds("  U4PRUY  ")

        XCTAssertEqual(lower, upperWithWhitespace)
    }

    func testDecodeBoundsThrowsOnEmptyString() {
        XCTAssertThrowsError(try GeohashGeometry.decodeBounds("")) { error in
            XCTAssertEqual(error as? GeohashDecodeError, .empty)
        }
        XCTAssertThrowsError(try GeohashGeometry.decodeBounds("   ")) { error in
            XCTAssertEqual(error as? GeohashDecodeError, .empty)
        }
    }

    func testDecodeBoundsThrowsOnInvalidCharacter() {
        // 'a', 'i', 'l', 'o' are not in the geohash base32 alphabet.
        XCTAssertThrowsError(try GeohashGeometry.decodeBounds("abc123")) { error in
            XCTAssertEqual(error as? GeohashDecodeError, .invalidCharacter("a"))
        }
    }

    // MARK: - polygonRing

    func testPolygonRingReturnsFiveClosedCornersOrderedSwNwNeSe() throws {
        let ring = try GeohashGeometry.polygonRing(for: "s0wzj9")
        let bounds = try GeohashGeometry.decodeBounds("s0wzj9")

        XCTAssertEqual(ring.count, 5)
        XCTAssertEqual(ring[0].latitude, bounds.south, accuracy: 1e-9)
        XCTAssertEqual(ring[0].longitude, bounds.west, accuracy: 1e-9)
        XCTAssertEqual(ring[1].latitude, bounds.north, accuracy: 1e-9)
        XCTAssertEqual(ring[1].longitude, bounds.west, accuracy: 1e-9)
        XCTAssertEqual(ring[2].latitude, bounds.north, accuracy: 1e-9)
        XCTAssertEqual(ring[2].longitude, bounds.east, accuracy: 1e-9)
        XCTAssertEqual(ring[3].latitude, bounds.south, accuracy: 1e-9)
        XCTAssertEqual(ring[3].longitude, bounds.east, accuracy: 1e-9)
        // Closed ring: last point == first point.
        XCTAssertEqual(ring[4].latitude, ring[0].latitude, accuracy: 1e-9)
        XCTAssertEqual(ring[4].longitude, ring[0].longitude, accuracy: 1e-9)
    }

    func testPolygonRingPropagatesInvalidGeohashError() {
        XCTAssertThrowsError(try GeohashGeometry.polygonRing(for: "!!!"))
    }

    // MARK: - IntensityNormalization

    func testNormalizeSingleValueClampsIntoZeroToOneRange() {
        XCTAssertEqual(IntensityNormalization.normalize(50, minValue: 0, maxValue: 100), 0.5, accuracy: 1e-9)
        XCTAssertEqual(IntensityNormalization.normalize(0, minValue: 0, maxValue: 100), 0.0, accuracy: 1e-9)
        XCTAssertEqual(IntensityNormalization.normalize(100, minValue: 0, maxValue: 100), 1.0, accuracy: 1e-9)
    }

    func testNormalizeClampsValuesOutsideTheProvidedRange() {
        XCTAssertEqual(IntensityNormalization.normalize(-20, minValue: 0, maxValue: 100), 0.0, accuracy: 1e-9)
        XCTAssertEqual(IntensityNormalization.normalize(150, minValue: 0, maxValue: 100), 1.0, accuracy: 1e-9)
    }

    func testNormalizeDegenerateRangeReturnsFullIntensityRatherThanDividingByZero() {
        // A single-cell dataset (min == max) must not collapse to 0 or NaN —
        // it should render at full intensity so it's still visible.
        XCTAssertEqual(IntensityNormalization.normalize(42, minValue: 42, maxValue: 42), 1.0, accuracy: 1e-9)
    }

    func testNormalizeArrayPreservesOrderAndNormalizesAgainstOwnMinMax() {
        let normalized = IntensityNormalization.normalize([10, 30, 20])

        XCTAssertEqual(normalized.count, 3)
        XCTAssertEqual(normalized[0], 0.0, accuracy: 1e-9)
        XCTAssertEqual(normalized[1], 1.0, accuracy: 1e-9)
        XCTAssertEqual(normalized[2], 0.5, accuracy: 1e-9)
    }

    func testNormalizeArrayOfEmptyInputReturnsEmpty() {
        XCTAssertTrue(IntensityNormalization.normalize([]).isEmpty)
    }

    func testNormalizeArrayOfSingleValueReturnsFullIntensity() {
        XCTAssertEqual(IntensityNormalization.normalize([77]), [1.0])
    }
}
