import Foundation

/// Lifecycle status of one queued draft. Mirrors `QueueStatus` (`'pending' |
/// 'syncing' | 'failed' | 'synced'`) in `lib/client/offlineQueue.ts` — though
/// `.synced` items are removed from the store immediately on success (same
/// as the web queue deleting from IndexedDB on sync), so in practice a
/// persisted item is always `.pending`, `.syncing`, or `.failed`; `.synced`
/// exists as a case for completeness / any future "keep synced history"
/// caller, and is what a freshly-synced item briefly transitions through.
public enum RecordQueueItemStatus: String, Codable, Equatable, Sendable {
    case pending
    case syncing
    case failed
    case synced
}

/// One persisted queue entry: a `RecordDraft` plus the bookkeeping needed to
/// sync it exactly once. `idempotencyKey` is assigned exactly once, at
/// `enqueue`, and never regenerated by a retry — it is sent as the
/// `Idempotency-Key` header on every submit attempt for this item, so a
/// server that saw an earlier attempt (e.g. the request succeeded but the
/// response was lost) can safely no-op a duplicate.
public struct RecordQueueItem: Codable, Equatable, Sendable, Identifiable {
    public var id: String
    public var idempotencyKey: String
    public var draft: RecordDraft
    public var status: RecordQueueItemStatus
    public var attempts: Int
    public var retryCount: Int
    public var nextRetryAt: Date?
    public var lastError: String?
    public var createdAt: Date
    public var updatedAt: Date

    public init(
        id: String,
        idempotencyKey: String,
        draft: RecordDraft,
        status: RecordQueueItemStatus,
        attempts: Int,
        retryCount: Int,
        nextRetryAt: Date? = nil,
        lastError: String? = nil,
        createdAt: Date,
        updatedAt: Date
    ) {
        self.id = id
        self.idempotencyKey = idempotencyKey
        self.draft = draft
        self.status = status
        self.attempts = attempts
        self.retryCount = retryCount
        self.nextRetryAt = nextRetryAt
        self.lastError = lastError
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

/// Counts of queued items by status, for a sync-status UI. Mirrors the
/// `pending`/`failed`/`total` shape `getQueueStats` exposes in
/// `lib/client/offlineQueue.ts`.
public struct RecordQueueSnapshot: Equatable, Sendable {
    public var pending: Int
    public var syncing: Int
    public var failed: Int
    public var total: Int
    public var syncedThisSession: Int

    public init(pending: Int, syncing: Int, failed: Int, total: Int, syncedThisSession: Int) {
        self.pending = pending
        self.syncing = syncing
        self.failed = failed
        self.total = total
        self.syncedThisSession = syncedThisSession
    }
}

/// Result of one `RecordQueue.sync(submit:)` pass. Mirrors `QueueSyncSummary`
/// in `lib/client/offlineQueue.ts`.
public struct RecordQueueSyncSummary: Equatable, Sendable {
    public var syncedIds: [String]
    public var failedIds: [String]
    public var permanentFailureIds: [String]
    public var remaining: Int

    public init(syncedIds: [String], failedIds: [String], permanentFailureIds: [String], remaining: Int) {
        self.syncedIds = syncedIds
        self.failedIds = failedIds
        self.permanentFailureIds = permanentFailureIds
        self.remaining = remaining
    }
}

public enum RecordQueueError: Error, Equatable, Sendable {
    /// Thrown by `enqueue` once the store already holds `RecordQueue.maxItems`
    /// items — mirrors `offlineQueue.ts`'s `enqueueSubmission` throwing when
    /// the queue is at `MAX_QUEUE_ITEMS` (75).
    case full(maxItems: Int)
}

/// A submit failure the injected submit closure can throw to control retry
/// behavior. Mirrors the `retryable` flag `toQueueErrorInfo` derives from a
/// thrown `Error` in `lib/client/offlineQueue.ts` (there, any `Error` without
/// an explicit `retryable: false` property defaults to retryable — here that
/// same default is expressed by *any other thrown error* also being treated
/// as `.retryable`, see `RecordQueue.sync`).
public enum RecordSubmitError: Error, Sendable {
    case retryable(String)
    case permanent(String)
}

/// The offline queue for captured `RecordDraft`s — a direct behavioral port
/// of `lib/client/offlineQueue.ts`'s `enqueueSubmission` / `flushOfflineQueue`
/// pair, adapted from IndexedDB + a bare `sendFn` to a `RecordQueueStore` +
/// an injected `submit` closure (which the app wires to
/// `PlatformAPIClient.createPlatformRecord`).
///
/// An `actor` so concurrent `enqueue`/`sync` calls from SwiftUI (main actor)
/// and a background sync trigger never race on the same store read-modify-
/// write cycle.
public actor RecordQueue {
    /// Mirrors `MAX_QUEUE_ITEMS` in `offlineQueue.ts`.
    public static let maxItems = 75
    /// Mirrors `MAX_QUEUE_RETRY_COUNT` in `offlineQueue.ts`.
    public static let maxRetryCount = 6
    /// Mirrors `MAX_QUEUE_ITEM_AGE_MS` (72h) in `offlineQueue.ts`.
    public static let maxItemAge: TimeInterval = 72 * 60 * 60

    public typealias SubmitClosure = @Sendable (_ draft: RecordDraft, _ idempotencyKey: String) async throws -> Void

    private let store: RecordQueueStore
    private let idGenerator: @Sendable () -> String
    private let idempotencyKeyGenerator: @Sendable () -> String
    private let now: @Sendable () -> Date
    private var syncedThisSession = 0

    public init(
        store: RecordQueueStore,
        idGenerator: @escaping @Sendable () -> String = { UUID().uuidString },
        idempotencyKeyGenerator: @escaping @Sendable () -> String = { UUID().uuidString },
        now: @escaping @Sendable () -> Date = { Date() }
    ) {
        self.store = store
        self.idGenerator = idGenerator
        self.idempotencyKeyGenerator = idempotencyKeyGenerator
        self.now = now
    }

    /// Persists a new draft as a `.pending` item with a freshly-generated,
    /// stable idempotency key. Throws `.full` once the store already holds
    /// `Self.maxItems` items, mirroring `enqueueSubmission`'s guard.
    @discardableResult
    public func enqueue(_ draft: RecordDraft) throws -> RecordQueueItem {
        var items = try store.load()
        guard items.count < Self.maxItems else {
            throw RecordQueueError.full(maxItems: Self.maxItems)
        }
        let timestamp = now()
        let item = RecordQueueItem(
            id: idGenerator(),
            idempotencyKey: idempotencyKeyGenerator(),
            draft: draft,
            status: .pending,
            attempts: 0,
            retryCount: 0,
            createdAt: timestamp,
            updatedAt: timestamp
        )
        items.append(item)
        try store.save(items)
        return item
    }

    /// All currently-persisted items, oldest first — mirrors `listQueueItems`.
    public func items() throws -> [RecordQueueItem] {
        try store.load().sorted { $0.createdAt < $1.createdAt }
    }

    public func snapshot() throws -> RecordQueueSnapshot {
        let items = try store.load()
        return RecordQueueSnapshot(
            pending: items.filter { $0.status == .pending }.count,
            syncing: items.filter { $0.status == .syncing }.count,
            failed: items.filter { $0.status == .failed }.count,
            total: items.count,
            syncedThisSession: syncedThisSession
        )
    }

    /// Removes every item, regardless of status. Exposed for a "clear queue"
    /// affordance / test teardown; not part of the sync lifecycle.
    public func removeAll() throws {
        try store.save([])
    }

    /// Attempts to sync every due item via `submit`, one at a time, in
    /// enqueue order. Behavior per item mirrors `flushOfflineQueue`:
    ///
    /// - Stale (older than `maxItemAge`): dropped as a permanent failure,
    ///   never submitted.
    /// - Not yet due (`nextRetryAt` in the future): skipped this pass,
    ///   counted as `failedIds` (still in the queue, still failing to sync).
    /// - `submit` succeeds: removed from the queue, counted as `syncedIds`.
    /// - `submit` throws `.retryable`: `retryCount` increments; once it
    ///   exceeds `maxRetryCount` the item is dropped as a permanent failure,
    ///   otherwise it's marked `.failed` with an exponential-backoff
    ///   `nextRetryAt` (capped at 30s; unlike the web queue this omits random
    ///   jitter, since `RecordQueue` favors deterministic, testable backoff
    ///   over jitter's thundering-herd mitigation, which matters less for a
    ///   single-device native client than a shared web backend).
    /// - `submit` throws `.permanent`, or throws anything else (an unknown
    ///   error type defaults to retryable, matching `toQueueErrorInfo`'s
    ///   default in `offlineQueue.ts`): `.permanent` drops immediately as a
    ///   permanent failure; any other thrown error is treated as `.retryable`
    ///   with its `String(describing:)` as the message.
    ///
    /// The idempotency key is never regenerated across retries — it was
    /// fixed at `enqueue` and is passed to `submit` unchanged every attempt.
    @discardableResult
    public func sync(submit: SubmitClosure) async -> RecordQueueSyncSummary {
        var items = (try? store.load()) ?? []
        let nowValue = now()

        var syncedIds: [String] = []
        var failedIds: [String] = []
        var permanentFailureIds: [String] = []

        var index = 0
        while index < items.count {
            let item = items[index]

            if nowValue.timeIntervalSince(item.createdAt) > Self.maxItemAge {
                permanentFailureIds.append(item.id)
                items.remove(at: index)
                continue
            }

            if let nextRetryAt = item.nextRetryAt, nextRetryAt > nowValue {
                failedIds.append(item.id)
                index += 1
                continue
            }

            items[index].status = .syncing
            items[index].attempts += 1
            items[index].updatedAt = nowValue

            do {
                try await submit(item.draft, item.idempotencyKey)
                syncedThisSession += 1
                syncedIds.append(item.id)
                items.remove(at: index)
            } catch {
                let (message, retryable) = Self.classify(error)
                if !retryable {
                    permanentFailureIds.append(item.id)
                    items.remove(at: index)
                    continue
                }
                let retryCount = items[index].retryCount + 1
                if retryCount > Self.maxRetryCount {
                    permanentFailureIds.append(item.id)
                    items.remove(at: index)
                    continue
                }
                items[index].status = .failed
                items[index].retryCount = retryCount
                items[index].lastError = message
                items[index].nextRetryAt = nowValue.addingTimeInterval(Self.backoffInterval(retryCount: retryCount))
                items[index].updatedAt = nowValue
                failedIds.append(item.id)
                index += 1
            }
        }

        try? store.save(items)
        return RecordQueueSyncSummary(
            syncedIds: syncedIds,
            failedIds: failedIds,
            permanentFailureIds: permanentFailureIds,
            remaining: items.count
        )
    }

    private static func classify(_ error: Error) -> (message: String, retryable: Bool) {
        switch error {
        case RecordSubmitError.retryable(let message):
            return (message, true)
        case RecordSubmitError.permanent(let message):
            return (message, false)
        default:
            // Unknown error type: default to retryable, matching
            // `toQueueErrorInfo`'s default in `offlineQueue.ts`.
            return (String(describing: error), true)
        }
    }

    /// Exponential backoff in seconds, capped at 30s — `2^retryCount`,
    /// mirroring `offlineQueue.ts`'s `min(30000, 1000 * 2^retryCount)`
    /// expressed in seconds rather than milliseconds.
    private static func backoffInterval(retryCount: Int) -> TimeInterval {
        min(30, pow(2, Double(retryCount)))
    }
}
